### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bjorn3** [ebobby/simple-raytracer#2]
Hi @ebobby I just noticed that this repo doesn't have a license. I've been using it for a while as benchmark for a compiler backend of mine. Would you mind licensing it under an open source license?

**Comment by ebobby** [comment]
Sorry I forgot to come back to you on this one. Ill add the license.

**Comment by bjorn3** [comment]
Thanks a lot! Just to confirm does it also apply to commit 804a7a21b9e673a482797aa289a18ed480e4d813? This is the specific commit I used as benchmark.

**Comment by ebobby** [comment]
Sure.
